var LANGUAGE_STORAGE_KEY = "meyman_language_v1";

var LANGUAGES = {
    en: { label: "English", flag: "🇺🇸", short: "EN" },
    ru: { label: "Русский", flag: "🇷🇺", short: "RU" },
    ky: { label: "Кыргызча", flag: "🇰🇬", short: "KG" }
};

var TRANSLATIONS = {
    en: {
        choose_language: "Choose your language",
        choose_language_subtitle: "Pick the language for the Meyman interface.",
        map: "Map",
        explore: "Explore",
        cultural_guide: "Cultural Guide",
        host_mode: "Host Mode",
        search_placeholder: "Search experiences, food, places...",
        hungry: "Hungry",
        nomad_life: "Nomad life",
        craft: "Craft",
        shower: "Shower",
        laundry: "Laundry",
        all: "All",
        eat_like_local: "Eat Like a Local 🍽️",
        nomad_life_category: "Nomad Life 🏔️",
        culture_craft: "Culture & Craft 🎨",
        essentials: "Essentials 🧼",
        motto: "Your lifestyle is their experience",
        happening_now: "Happening Now 🔥",
        eat_like_local_short: "🍽️ Eat Like a Local",
        nomad_craft_short: "🏔️ Nomad Life & Craft",
        discover: "Discover",
        request_experience: "Request an Experience",
        request_desc: "Can't find what you're looking for? Ask locals directly.",
        category: "Category",
        request_what: "What are you looking for?",
        request_placeholder: "Example: I'd love to learn how to cook traditional plov...",
        submit_request: "Submit Request",
        leave_review: "Leave a Review",
        review_desc: "How was your experience? Your feedback helps the community!",
        rating_label: "Rating (1-5)",
        your_comment: "Your Comment",
        review_placeholder: "Tell us what you liked or how the host can improve...",
        submit_review: "Submit Review",
        new: "New",
        bookings: "Bookings",
        inbox: "Inbox",
        profile: "Profile",
        available_now: "Available now",
        starting_soon: "Starting soon",
        no_experiences_now: "No experiences happening right now.",
        spots_left: "{count} spots left",
        fully_booked: "Fully Booked",
        booked_today: "Booked today, {time}",
        booked_on: "Booked {date}",
        confirmed: "Confirmed",
        review: "Review",
        paid_with: "Paid with {method}",
        booked_successfully: "Booked Successfully",
        booking_in_tab: "{title} is in your Bookings tab.",
        meet_host_eta: "Meet {host} in about {eta}.",
        view_booking: "View booking",
        directions: "Directions",
        direction_step_1: "📍 Meet near central Bishkek landmark",
        direction_step_2: "🚶 {eta} from your current area",
        direction_step_3: "✅ Show this confirmation when you arrive",
        payment_methods: "Payment methods",
        choose_how_to_pay: "Choose how to pay",
        total: "Total",
        pay_now: "Pay Now",
        pay_terms: "By tapping Pay Now, you confirm this demo booking and payment method.",
        no_bookings_yet: "No bookings yet.\n\nBook something nearby and it will appear here instantly.",
        support_welcome: "Welcome to Meyman! Explore our local experiences.",
        thanks_for_booking: "Thanks for booking {title}! See you soon.",
        traveler_profile_name: "Traveler",
        joined_april_2026: "Joined April 2026",
        payment_methods_arrow: "Payment Methods",
        language_setting: "Language ({code})",
        log_out: "Log Out",
        active_offers: "Active Offers",
        total_bookings: "Total Bookings",
        total_earnings: "Total Earnings",
        total_reviews: "Total Reviews",
        your_offers: "Your Offers",
        view_all: "View all",
        quick_actions: "Quick Actions",
        create_new_offer: "Create New\nOffer",
        calendar_availability: "Calendar /\nAvailability",
        earnings: "Earnings",
        messages: "Messages",
        customer_requests: "Customer Requests",
        seller_greeting: "Salam, Aigul! 👋",
        seller_location: "📍 Bishkek, Kyrgyzstan",
        code_of_conduct: "Code of Conduct",
        host_conduct_title: "Host Code of Conduct",
        host_conduct_desc: "Complete 4 quick scenarios to unlock Verified Host.",
        start: "Start",
        create_offer: "Create an Offer",
        offering_label: "What are you offering?",
        offering_placeholder: "Example: Home cooked dinner",
        price_label: "Price (KGS)",
        spots_available: "Spots Available",
        publish_offer: "Publish Offer",
        fill_all_details: "Please fill in all details.",
        offer_published: "Offer published successfully!",
        publish_failed: "Failed to publish offer: {error}",
        request_received: "New Request Received",
        request_looking_for_food: "{guest} is looking for a food experience.",
        mins_ago: "{count} mins ago",
        earnings_transferred: "Earnings Transferred",
        funds_sent: "{amount} has been sent to your linked card.",
        yesterday: "Yesterday",
        menu: "Menu",
        notifications: "Notifications",
        host_settings: "Host Settings",
        manage_payments: "Manage Payments",
        help_support: "Help & Support",
        switch_to_tourist: "Switch to Tourist Mode",
        calendar: "Calendar",
        payment_methods_linked: "Linked payouts: MBANK, Visa / MasterCard, and cash terminals.",
        language_pref_here: "Language preferences will live here. English is active for the demo.",
        provider_name: "Aizada | Nomad Host",
        trusted_local: "Trusted Local ⭐",
        view_public_profile: "View Public Profile",
        guests_served: "Guests Served",
        completion_rate: "Completion Rate",
        your_services: "Your Services",
        add_service: "+ Add Service",
        active: "Active",
        needs_fix: "Needs Fix",
        edit: "Edit",
        view: "View",
        pending_payments: "Pending Payments",
        platform_fee: "Platform Fee",
        guest_feedback: "Guest Feedback",
        needs_attention: "Needs Attention ⚠️",
        everything_good: "Everything looks good ✅",
        profile_strength: "Profile Strength",
        view_badges: "🏅 View Badges",
        add_more_services: "Add more services",
        resolve_service_issues: "Resolve service issues",
        add_more_photos: "Add more photos",
        update_availability: "Update availability",
        your_badges: "Your Badges",
        no_guest_feedback: "No guest feedback yet.",
        reply: "Reply",
        public_profile_preview: "Public provider profile preview opened for demo.",
        edit_service: "Edit Service",
        service_details: "Service Details",
        fix_this_service: "Fix This Service",
        quick_edit_coming: "Quick edit tools coming next.",
        reply_composer_opened: "Reply composer opened for review {id}.",
        no_active_offers: "You have no active offers.\n\nClick the Create button to get started!",
        no_customer_requests: "No customer requests right now.",
        accept: "Accept",
        you_offered_fulfill: "You have offered to fulfill this request! The customer will be notified.",
        fulfill_failed: "Failed to fulfill request: {error}",
        booking_failed: "Booking failed: {error}",
        request_missing: "Please describe what you are looking for!",
        request_sent: "Your request has been sent to locals nearby!",
        review_missing: "Please write a short comment for your review!",
        review_thanks: "Thank you! Your review has been published.",
        review_failed: "Failed to submit review: {error}",
        payment_detail_mbank: "Fast local bank transfer",
        payment_detail_visa: "International cards accepted",
        payment_detail_o: "Mobile wallet",
        payment_detail_megapay: "QR or app payment",
        payment_detail_optima: "Local banking app",
        payment_detail_bakai: "Bank wallet",
        payment_detail_terminal: "Pay24, Quickpay, Onoi",
        live: "LIVE",
        language_button: "Language"
    },
    ru: {
        choose_language: "Выберите язык",
        choose_language_subtitle: "Выберите язык интерфейса Meyman.",
        map: "Карта",
        explore: "Лента",
        cultural_guide: "Культурный гид",
        host_mode: "Режим хоста",
        search_placeholder: "Ищите впечатления, еду, места...",
        hungry: "Поесть",
        nomad_life: "Кочевая жизнь",
        craft: "Ремесло",
        shower: "Душ",
        laundry: "Прачечная",
        all: "Все",
        eat_like_local: "Еда по-местному 🍽️",
        nomad_life_category: "Кочевая жизнь 🏔️",
        culture_craft: "Культура и ремесло 🎨",
        essentials: "Базовые услуги 🧼",
        motto: "Ваш образ жизни — их впечатление",
        happening_now: "Доступно сейчас 🔥",
        eat_like_local_short: "🍽️ Еда по-местному",
        nomad_craft_short: "🏔️ Кочевая жизнь и ремесло",
        discover: "Открывайте",
        request_experience: "Запросить впечатление",
        request_desc: "Не нашли нужное? Спросите местных напрямую.",
        category: "Категория",
        request_what: "Что вы ищете?",
        request_placeholder: "Например: хочу научиться готовить традиционный плов...",
        submit_request: "Отправить запрос",
        leave_review: "Оставить отзыв",
        review_desc: "Как прошло впечатление? Ваш отзыв помогает сообществу!",
        rating_label: "Оценка (1-5)",
        your_comment: "Ваш комментарий",
        review_placeholder: "Напишите, что вам понравилось или что можно улучшить...",
        submit_review: "Отправить отзыв",
        new: "Новый",
        bookings: "Бронирования",
        inbox: "Входящие",
        profile: "Профиль",
        available_now: "Доступно сейчас",
        starting_soon: "Скоро начнется",
        no_experiences_now: "Сейчас нет доступных впечатлений.",
        spots_left: "Осталось мест: {count}",
        fully_booked: "Мест нет",
        booked_today: "Забронировано сегодня, {time}",
        booked_on: "Забронировано {date}",
        confirmed: "Подтверждено",
        review: "Отзыв",
        paid_with: "Оплачено через {method}",
        booked_successfully: "Успешно забронировано",
        booking_in_tab: "{title} теперь в разделе бронирований.",
        meet_host_eta: "Встреча с {host} примерно через {eta}.",
        view_booking: "Открыть бронь",
        directions: "Маршрут",
        direction_step_1: "📍 Встреча у центрального ориентира Бишкека",
        direction_step_2: "🚶 {eta} от вашего текущего места",
        direction_step_3: "✅ Покажите это подтверждение по прибытии",
        payment_methods: "Способы оплаты",
        choose_how_to_pay: "Выберите способ оплаты",
        total: "Итого",
        pay_now: "Оплатить",
        pay_terms: "Нажимая «Оплатить», вы подтверждаете демо-бронирование и способ оплаты.",
        no_bookings_yet: "Пока нет бронирований.\n\nЗабронируйте что-нибудь рядом, и оно сразу появится здесь.",
        support_welcome: "Добро пожаловать в Meyman! Открывайте местные впечатления.",
        thanks_for_booking: "Спасибо за бронирование {title}! До встречи.",
        traveler_profile_name: "Путешественник",
        joined_april_2026: "С нами с апреля 2026",
        payment_methods_arrow: "Способы оплаты",
        language_setting: "Язык ({code})",
        log_out: "Выйти",
        active_offers: "Активные услуги",
        total_bookings: "Всего бронирований",
        total_earnings: "Общий доход",
        total_reviews: "Всего отзывов",
        your_offers: "Ваши услуги",
        view_all: "Смотреть все",
        quick_actions: "Быстрые действия",
        create_new_offer: "Создать\nуслугу",
        calendar_availability: "Календарь /\nДоступность",
        earnings: "Доход",
        messages: "Сообщения",
        customer_requests: "Запросы гостей",
        seller_greeting: "Салам, Айгуль! 👋",
        seller_location: "📍 Бишкек, Кыргызстан",
        code_of_conduct: "Кодекс поведения",
        host_conduct_title: "Кодекс поведения хоста",
        host_conduct_desc: "Пройдите 4 коротких сценария и получите статус Verified Host.",
        start: "Начать",
        create_offer: "Создать услугу",
        offering_label: "Что вы предлагаете?",
        offering_placeholder: "Например: домашний ужин",
        price_label: "Цена (сом)",
        spots_available: "Доступные места",
        publish_offer: "Опубликовать",
        fill_all_details: "Пожалуйста, заполните все поля.",
        offer_published: "Услуга успешно опубликована!",
        publish_failed: "Не удалось опубликовать: {error}",
        request_received: "Новый запрос",
        request_looking_for_food: "{guest} ищет гастрономическое впечатление.",
        mins_ago: "{count} мин назад",
        earnings_transferred: "Доход переведен",
        funds_sent: "{amount} отправлено на вашу карту.",
        yesterday: "Вчера",
        menu: "Меню",
        notifications: "Уведомления",
        host_settings: "Настройки хоста",
        manage_payments: "Управление выплатами",
        help_support: "Помощь и поддержка",
        switch_to_tourist: "Переключиться в режим гостя",
        calendar: "Календарь",
        payment_methods_linked: "Подключены выплаты: MBANK, Visa / MasterCard и терминалы.",
        language_pref_here: "Здесь будут настройки языка. Для демо выбран русский.",
        provider_name: "Айзада | Номад-хост",
        trusted_local: "Надежный местный ⭐",
        view_public_profile: "Публичный профиль",
        guests_served: "Гостей обслужено",
        completion_rate: "Процент завершения",
        your_services: "Ваши услуги",
        add_service: "+ Добавить услугу",
        active: "Активно",
        needs_fix: "Нужно исправить",
        edit: "Изменить",
        view: "Открыть",
        pending_payments: "Ожидают выплаты",
        platform_fee: "Комиссия платформы",
        guest_feedback: "Отзывы гостей",
        needs_attention: "Требует внимания ⚠️",
        everything_good: "Все выглядит хорошо ✅",
        profile_strength: "Сила профиля",
        view_badges: "🏅 Награды",
        add_more_services: "Добавьте больше услуг",
        resolve_service_issues: "Исправьте проблемы в услугах",
        add_more_photos: "Добавьте больше фото",
        update_availability: "Обновите доступность",
        your_badges: "Ваши награды",
        no_guest_feedback: "Пока нет отзывов гостей.",
        reply: "Ответить",
        public_profile_preview: "Открыт демо-просмотр публичного профиля провайдера.",
        edit_service: "Изменить услугу",
        service_details: "Детали услуги",
        fix_this_service: "Исправить услугу",
        quick_edit_coming: "Инструменты быстрого редактирования скоро появятся.",
        reply_composer_opened: "Открыт ответ на отзыв {id}.",
        no_active_offers: "У вас пока нет активных услуг.\n\nНажмите «Создать», чтобы начать!",
        no_customer_requests: "Сейчас нет запросов от гостей.",
        accept: "Принять",
        you_offered_fulfill: "Вы предложили выполнить этот запрос! Гость будет уведомлен.",
        fulfill_failed: "Не удалось принять запрос: {error}",
        booking_failed: "Ошибка бронирования: {error}",
        request_missing: "Пожалуйста, опишите, что вы ищете!",
        request_sent: "Ваш запрос отправлен местным жителям поблизости!",
        review_missing: "Пожалуйста, напишите короткий комментарий!",
        review_thanks: "Спасибо! Ваш отзыв опубликован.",
        review_failed: "Не удалось отправить отзыв: {error}",
        payment_detail_mbank: "Быстрый перевод через местный банк",
        payment_detail_visa: "Принимаются международные карты",
        payment_detail_o: "Мобильный кошелек",
        payment_detail_megapay: "Оплата по QR или в приложении",
        payment_detail_optima: "Локальное банковское приложение",
        payment_detail_bakai: "Банковский кошелек",
        payment_detail_terminal: "Pay24, Quickpay, Onoi",
        live: "СЕЙЧАС",
        language_button: "Язык"
    },
    ky: {
        choose_language: "Тилди тандаңыз",
        choose_language_subtitle: "Meyman интерфейсинин тилин тандаңыз.",
        map: "Карта",
        explore: "Тасма",
        cultural_guide: "Маданий гид",
        host_mode: "Хост режими",
        search_placeholder: "Тажрыйба, тамак же жер издеңиз...",
        hungry: "Тамак",
        nomad_life: "Көчмөн жашоо",
        craft: "Өнөр",
        shower: "Душ",
        laundry: "Кир жуучу жай",
        all: "Баары",
        eat_like_local: "Жергиликтүүдөй тамак 🍽️",
        nomad_life_category: "Көчмөн жашоо 🏔️",
        culture_craft: "Маданият жана өнөр 🎨",
        essentials: "Керектүү кызматтар 🧼",
        motto: "Сиздин жашоо образыңыз — алардын тажрыйбасы",
        happening_now: "Азыр жеткиликтүү 🔥",
        eat_like_local_short: "🍽️ Жергиликтүүдөй тамак",
        nomad_craft_short: "🏔️ Көчмөн жашоо жана өнөр",
        discover: "Ачыңыз",
        request_experience: "Тажрыйба сураңыз",
        request_desc: "Керектүүсүн таппай жатасызбы? Жергиликтүүлөрдөн түз сураңыз.",
        category: "Категория",
        request_what: "Сиз эмнени издеп жатасыз?",
        request_placeholder: "Мисалы: салттуу плов жасоону үйрөнгүм келет...",
        submit_request: "Суроо жөнөтүү",
        leave_review: "Пикир калтыруу",
        review_desc: "Тажрыйба кандай өттү? Сиздин пикириңиз коомчулукка жардам берет!",
        rating_label: "Баалоо (1-5)",
        your_comment: "Комментарийиңиз",
        review_placeholder: "Эмне жакканын же эмнени жакшыртса болорун жазыңыз...",
        submit_review: "Пикир жөнөтүү",
        new: "Жаңы",
        bookings: "Ээлөөлөр",
        inbox: "Кириш кутусу",
        profile: "Профиль",
        available_now: "Азыр жеткиликтүү",
        starting_soon: "Жакында башталат",
        no_experiences_now: "Азыр жеткиликтүү тажрыйбалар жок.",
        spots_left: "{count} орун калды",
        fully_booked: "Орун жок",
        booked_today: "Бүгүн ээленди, {time}",
        booked_on: "{date} күнү ээленди",
        confirmed: "Тастыкталды",
        review: "Пикир",
        paid_with: "{method} аркылуу төлөндү",
        booked_successfully: "Ийгиликтүү ээленди",
        booking_in_tab: "{title} эми Ээлөөлөр бөлүмүндө.",
        meet_host_eta: "{host} менен болжол менен {eta} кийин жолугасыз.",
        view_booking: "Ээлөөнү ачуу",
        directions: "Багыт",
        direction_step_1: "📍 Борбордук ориентир жанынан жолугуңуз",
        direction_step_2: "🚶 Учурдагы жериңизден {eta}",
        direction_step_3: "✅ Барганда ушул ырастоону көрсөтүңүз",
        payment_methods: "Төлөм ыкмалары",
        choose_how_to_pay: "Кантип төлөйсүз?",
        total: "Жалпы",
        pay_now: "Төлөө",
        pay_terms: "«Төлөө» баскычы аркылуу демо-ээлөөнү жана төлөм ыкмасын тастыктайсыз.",
        no_bookings_yet: "Азырынча ээлөөлөр жок.\n\nЖакын жерден бир нерсени ээлесеңиз, ал бул жерде дароо көрүнөт.",
        support_welcome: "Meyman'га кош келиңиз! Жергиликтүү тажрыйбаларды ачыңыз.",
        thanks_for_booking: "{title} ээлегениңиз үчүн рахмат! Жакында көрүшөбүз.",
        traveler_profile_name: "Саякатчы",
        joined_april_2026: "2026-жылдын апрелинен бери",
        payment_methods_arrow: "Төлөм ыкмалары",
        language_setting: "Тил ({code})",
        log_out: "Чыгуу",
        active_offers: "Активдүү кызматтар",
        total_bookings: "Жалпы ээлөөлөр",
        total_earnings: "Жалпы киреше",
        total_reviews: "Жалпы пикирлер",
        your_offers: "Сиздин кызматтар",
        view_all: "Баарын көрүү",
        quick_actions: "Тез аракеттер",
        create_new_offer: "Жаңы\nкызмат түзүү",
        calendar_availability: "Календарь /\nЖеткиликтүүлүк",
        earnings: "Киреше",
        messages: "Билдирүүлөр",
        customer_requests: "Коноктордун суроолору",
        seller_greeting: "Салам, Айгүл! 👋",
        seller_location: "📍 Бишкек, Кыргызстан",
        code_of_conduct: "Жүрүм-турум эрежеси",
        host_conduct_title: "Хосттун жүрүм-турум эрежеси",
        host_conduct_desc: "4 кыска сценарийди өтүп, Verified Host белгисин ачыңыз.",
        start: "Баштоо",
        create_offer: "Кызмат түзүү",
        offering_label: "Эмне сунуштайсыз?",
        offering_placeholder: "Мисалы: үйдө жасалган кечки тамак",
        price_label: "Баасы (сом)",
        spots_available: "Жеткиликтүү орундар",
        publish_offer: "Жарыялоо",
        fill_all_details: "Сураныч, бардык талааларды толтуруңуз.",
        offer_published: "Кызмат ийгиликтүү жарыяланды!",
        publish_failed: "Жарыялоо мүмкүн болгон жок: {error}",
        request_received: "Жаңы суроо келди",
        request_looking_for_food: "{guest} тамак тажрыйбасын издеп жатат.",
        mins_ago: "{count} мүнөт мурун",
        earnings_transferred: "Киреше которулду",
        funds_sent: "{amount} картаңызга жөнөтүлдү.",
        yesterday: "Кечээ",
        menu: "Меню",
        notifications: "Эскертмелер",
        host_settings: "Хост жөндөөлөрү",
        manage_payments: "Төлөмдөрдү башкаруу",
        help_support: "Жардам жана колдоо",
        switch_to_tourist: "Конок режими",
        calendar: "Календарь",
        payment_methods_linked: "Туташкан төлөмдөр: MBANK, Visa / MasterCard жана терминалдар.",
        language_pref_here: "Бул жерде тил жөндөөлөрү болот. Демо үчүн кыргыз тили тандалды.",
        provider_name: "Айзада | Номад хост",
        trusted_local: "Ишенимдүү жергиликтүү ⭐",
        view_public_profile: "Ачык профиль",
        guests_served: "Кызмат алган коноктор",
        completion_rate: "Аяктоо көрсөткүчү",
        your_services: "Сиздин кызматтар",
        add_service: "+ Кызмат кошуу",
        active: "Активдүү",
        needs_fix: "Оңдоо керек",
        edit: "Түзөтүү",
        view: "Көрүү",
        pending_payments: "Күтүүдөгү төлөмдөр",
        platform_fee: "Платформа комиссиясы",
        guest_feedback: "Коноктордун пикири",
        needs_attention: "Көңүл буруу керек ⚠️",
        everything_good: "Баары жакшы көрүнөт ✅",
        profile_strength: "Профиль күчү",
        view_badges: "🏅 Белгилерди көрүү",
        add_more_services: "Көбүрөөк кызмат кошуңуз",
        resolve_service_issues: "Кызмат маселелерин оңдоңуз",
        add_more_photos: "Көбүрөөк сүрөт кошуңуз",
        update_availability: "Жеткиликтүүлүктү жаңыртыңыз",
        your_badges: "Сиздин белгилер",
        no_guest_feedback: "Азырынча конок пикирлери жок.",
        reply: "Жооп берүү",
        public_profile_preview: "Провайдердин ачык профилинин демо көрүнүшү ачылды.",
        edit_service: "Кызматты түзөтүү",
        service_details: "Кызматтын чоо-жайы",
        fix_this_service: "Бул кызматты оңдоо",
        quick_edit_coming: "Тез түзөтүү куралдары жакында кошулат.",
        reply_composer_opened: "{id} пикири үчүн жооп терезеси ачылды.",
        no_active_offers: "Азырынча активдүү кызматыңыз жок.\n\nБаштоо үчүн «Түзүү» баскычын басыңыз!",
        no_customer_requests: "Азыр коноктордон суроо жок.",
        accept: "Кабыл алуу",
        you_offered_fulfill: "Бул суроону аткарууга макул болдуңуз! Конокко билдирүү жөнөтүлөт.",
        fulfill_failed: "Суроону кабыл алуу мүмкүн болгон жок: {error}",
        booking_failed: "Ээлөө ишке ашкан жок: {error}",
        request_missing: "Сураныч, эмнени издеп жатканыңызды жазыңыз!",
        request_sent: "Сурооңуз жакын жердеги жергиликтүүлөргө жөнөтүлдү!",
        review_missing: "Сураныч, кыска комментарий жазыңыз!",
        review_thanks: "Рахмат! Сиздин пикириңиз жарыяланды.",
        review_failed: "Пикир жөнөтүлбөдү: {error}",
        payment_detail_mbank: "Жергиликтүү банк аркылуу тез которуу",
        payment_detail_visa: "Эл аралык карталар кабыл алынат",
        payment_detail_o: "Мобилдик капчык",
        payment_detail_megapay: "QR же тиркеме аркылуу төлөм",
        payment_detail_optima: "Жергиликтүү банк тиркемеси",
        payment_detail_bakai: "Банк капчыгы",
        payment_detail_terminal: "Pay24, Quickpay, Onoi",
        live: "АЗЫР",
        language_button: "Тил"
    }
};

function getCurrentLanguage() {
    return localStorage.getItem(LANGUAGE_STORAGE_KEY) || "";
}

function getSafeLanguage() {
    var current = getCurrentLanguage();
    return LANGUAGES[current] ? current : "en";
}

function translate(key, vars) {
    var lang = getSafeLanguage();
    var dictionary = TRANSLATIONS[lang] || TRANSLATIONS.en;
    var text = dictionary[key] || TRANSLATIONS.en[key] || key;

    if (!vars) return text;

    for (var name in vars) {
        if (Object.prototype.hasOwnProperty.call(vars, name)) {
            text = text.replace(new RegExp("\\{" + name + "\\}", "g"), vars[name]);
        }
    }

    return text;
}

function t(key, vars) {
    return translate(key, vars);
}

function getLanguageShortCode() {
    return LANGUAGES[getSafeLanguage()].short;
}

function setLanguage(lang) {
    if (!LANGUAGES[lang]) lang = "en";
    localStorage.setItem(LANGUAGE_STORAGE_KEY, lang);
    document.documentElement.lang = lang;
    closeLanguageSelector();
    if (typeof window.applyAppTranslations === "function") window.applyAppTranslations();
}

function buildLanguageModal(forceChoice) {
    var modal = document.getElementById("language-modal");
    if (!modal) {
        modal = document.createElement("div");
        modal.id = "language-modal";
        modal.className = "language-modal-overlay hidden";
        document.body.appendChild(modal);
    }

    var closeButton = forceChoice ? "" : '<button class="btn-icon language-close" onclick="closeLanguageSelector()">✕</button>';
    modal.innerHTML =
        '<div class="language-card">' +
            '<div class="language-card-top">' +
                '<div>' +
                    '<div class="language-title">' + t("choose_language") + '</div>' +
                    '<div class="language-subtitle">' + t("choose_language_subtitle") + '</div>' +
                '</div>' +
                closeButton +
            '</div>' +
            '<div class="language-option-list">' +
                renderLanguageOption("en") +
                renderLanguageOption("ru") +
                renderLanguageOption("ky") +
            '</div>' +
        '</div>';
}

function renderLanguageOption(lang) {
    var item = LANGUAGES[lang];
    var activeClass = getSafeLanguage() === lang ? " active" : "";
    return '' +
        '<button class="language-option' + activeClass + '" onclick="setLanguage(\'' + lang + '\')">' +
            '<span class="language-flag">' + item.flag + '</span>' +
            '<span class="language-copy">' +
                '<span class="language-name">' + item.label + '</span>' +
                '<span class="language-code">' + item.short + '</span>' +
            '</span>' +
        '</button>';
}

function openLanguageSelector(forceChoice) {
    buildLanguageModal(!!forceChoice);
    document.getElementById("language-modal").classList.remove("hidden");
}

function closeLanguageSelector() {
    var modal = document.getElementById("language-modal");
    if (modal) modal.classList.add("hidden");
}

function initializeLanguageSystem() {
    document.documentElement.lang = getSafeLanguage();
    if (!getCurrentLanguage()) {
        openLanguageSelector(true);
    }
}

function getCategoryLabel(category) {
    var map = {
        "Eat Like a Local 🍽️": "eat_like_local",
        "Nomad Life 🏔️": "nomad_life_category",
        "Culture & Craft 🎨": "culture_craft",
        "Essentials 🧼": "essentials",
        "All": "all"
    };
    return t(map[category] || category);
}
